### ISSUE TITLE
Models with a space in name result in link follower breaking

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/py-capellambse#35] opened 2021-11-30 11:04 UTC
Use of models with space in name results in failure to render diagrams. We can then see the diagram name, uuid and description. But any call that involves renderer (i.e .nodes or actual svg preview) will fail with `ValueError: Malformed link: 'test 5.1.aird#_r-0YcAauEeydodL3xp60Ww'`

The failure occurs in regex of `follow_link` method of `MelodyLoader` in `loader.core` module

Steps to reproduce:

1. Create a new test model with Capella 5.1, create a sample LAB diagram
2. Create a new Jupyter notebook
3. Load test model in Jupyter with `model = capellambse.MelodyModel("test.aird")`
4. List the diagrams with `model.diagrams`
5. Visualize the lab diagram by index with `model.diagrams[idx]` where idx is a number from the above list

**Comment by ewuerger** [comment] 2021-11-30 15:12
Solution:
We need to fix the [linkmatch regex-pattern](https://github.com/DSD-DBS/py-capellambse/blob/ce7e8c785ebee969ea79be70cd5e6c3f1fe12401/capellambse/loader/core.py#L705) in loader/core.py.
The match is None for links that contain whitespace.

**Comment by ewuerger** [comment] 2021-11-30 15:56
Ok, if one is able to read doc-strings, one can gather knowledge about the expected format of the link parameter:
![image](https://user-images.githubusercontent.com/50786483/144081540-c4e25a43-f3c6-4f15-844a-a418383580b9.png)
My bad @Wuestengecko :+1:

**Comment by vik378** [comment] 2021-12-01 08:46
I'm not sure if thats the way to go as XML has those spaces URL-encoded (%20). So we wouldnt be in a situation where we need to handle multiple spaces and figureout what belongs to xtype and what to fragment name if we were not rendering %20 upfront. So what we should look into is the place in code where we render %20 and defer that action.

**Comment by Wuestengecko** [comment] 2021-12-02 11:24
> The pattern is interesting since it's destined to also catch an <xtype>. I've never seen such a case,...

It's used all the time in cross-fragment links (at least between semantic fragments, i.e. `.capellafragments`). Most models don't have more than two fragments though, which are the main `.aird` and the main `.capella` file.

> We change the pattern […]. Additonally we check if a fix is needed

I agree with @vik378 here, if knowing is an option then guessing is definitely not the right choice.

I do see slightly different behavior, which is a `KeyError` due to no matches being found, but ultimately it's the same problem. Curiously, looking at the code, the actual error raised should probably be a `FileNotFoundError` (with only part of the fragment's name, due the the whitespace issue), at least in my case. But that is a different can of worms.

Walking up the stack trace of the error, I found this interesting line: https://github.com/DSD-DBS/py-capellambse/blob/73729076aa8c38728f0db224002dab589118cd31/capellambse/aird/parser/__init__.py#L179

The `descriptor.fragment` that is referenced here is a `PurePosixPath` instance with the URL-**de**coded file name in it. This seems to be the root cause of the crash, and presumably also the reason why it only happens during diagram rendering (as in: hasn't been observed anywhere else for now).

Since we have the ability to create cross-fragment links, but we do not URL-encode the target fragment name, **this issue poses a severe risk of breaking models if any fragment's name contains whitespace** (or possibly other special characters): https://github.com/DSD-DBS/py-capellambse/blob/master/capellambse/loader/core.py#L669..L675

There really isn't a quick and easy fix for this issue though. If we just add URL-encoding to the line mentioned above, as we have more deep-rooted issues with space (and special char) handling in file names. Basically, every time we receive a filename somewhere, we must decode it, and every time we pass one, we must first encode it. That just never happens anywhere, and it leads to basically every cross-fragment link being broken if the target fragment has a space in its name. (3cdec41 already dealt with this exact issue, but the fix was very limited in scope and barely makes models loadable at all.)

(And how did a commit explicitly marked "`[WIP]`" end up as the branch tip of `master`?)

**Closed** 2021-12-13 12:41 UTC
Labels: bug, model breaking
