### ISSUE TITLE
Broken diagram SVG in documentation 

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/py-capellambse#331] opened 2023-08-29 09:58 UTC
Currently the describing `crosslayer.information` package [diagram is broken](https://dsd-dbs.github.io/py-capellambse/code/capellambse.model.crosslayer.information.html).

**Comment by Wuestengecko** [comment] 2023-09-07 11:02
Nothing beats the good old "Lines are parallel".

```
Traceback (most recent call last):
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/model/diagram.py", line 355, in __render_fresh
    self._render = self._create_diagram(params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/model/diagram.py", line 463, in _create_diagram
    return aird.parse_diagram(self._model._loader, self._element, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/__init__.py", line 188, in parse_diagram
    elm = _element_from_xml(
          ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/__init__.py", line 220, in _element_from_xml
    return factory(ebd)
           ^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_semantic.py", line 96, in from_xml
    return drawtype(seb)
           ^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 589, in association_factory
    edge = generic_factory(seb)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 65, in generic_factory
    snaptarget(edge, -1, -2, targetport, not edge.hidden, routingstyle)
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 293, in snaptarget
    snap_oblique(points, i, next_i, target)
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 303, in snap_oblique
    points[i] = target.vector_snap(
                ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/diagram/_diagram.py", line 261, in vector_snap
    return self.__vector_snap_oblique(source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/diagram/_diagram.py", line 277, in __vector_snap_oblique
    return diagram.line_intersect(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/diagram/_vector2d.py", line 375, in line_intersect
    raise ValueError("Lines are parallel")
ValueError: Lines are parallel
```

**Comment by Wuestengecko** [comment] 2023-09-14 15:57
Duplicate of #229.

**Closed by Wuestengecko** 2023-09-14 15:57 UTC
Labels: bug, documentation
